- name: Load users
  ansible.builtin.include_vars:
    dir: "{{ conf_dir ~ '/users' }}"

- name: When admin.uids not defined, use the ansible_user as admin
  set_fact:
    undef_admins_uid:
      - id: 1000
        name: "{{ lookup('vars','ansible_user') }}"
        shell: '/bin/bash'
    undef_admins_gid:
      - id: 100
        name: 'users'
    undef_admins_uids:
      - undef_admins_uid
    undef_admins_gids:
      - undef_admins_gid
    undef_admins:
      - uids: 'undef_admins_uids'
        gids: 'undef_admins_gids'

- name: Defaults admins and users
  set_fact:
    admins: "{{admins | default(undef_admins, true)}}"
    users: "{{users | default([], true)}}"

- name: uids
  set_fact:
    admins_uids: "{{ admins | map(attribute = 'uids') }}"
    admins_gids: "{{ admins | map(attribute = 'gids') }}"
    users_uids: "{{ users | map(attribute = 'uids') }}"
    users_gids: "{{ users | map(attribute = 'gids') }}"
    all_uids: "{{ (admins + users) | map(attribute = 'uids') }}"
    all_gids: "{{ (admins + users) | map(attribute = 'gids') }}"

- name: ensure all_[g,u]ids are defined
  assert:
    that:
      - item is defined
      - lookup('vars', item, default = '') | length > 0
    msg: "variable '{{ item }}' is undefined or empty but used in users or inventory"
  loop: "{{ all_uids + all_gids }}"

- name: dereference all_uids into _l1
  set_fact:
    all_uids_l1: "{{ all_uids_l1 | default([]) + [ lookup('vars', item) ] | flatten }}"
  loop: "{{ all_uids }}"

- name: dereference all_gids into _l1
  set_fact:
    all_gids_l1: "{{ all_gids_l1 | default([]) + [ lookup('vars', item) ] | flatten }}"
  loop: "{{ all_gids }}"

- name: ensure all_[g,u]ids_l1 are defined
  assert:
    that:
      - item is defined
      - lookup('vars', item, default = '') | length > 0
    msg: "variable '{{ item }}' is undefined or empty but used in users or inventory"
  loop: "{{ all_uids_l1 + all_gids_l1 }}"

- name: dereference all_uids_1 into _l2
  set_fact:
    all_uids_l2: "{{ all_uids_l2 | default([]) + [ lookup('vars', item) ] | flatten }}"
  loop: "{{ all_uids_l1 }}"

- name: dereference all_gids_l1 into _l2
  set_fact:
    all_gids_l2: "{{ all_gids_l2 | default([]) + [ lookup('vars', item) ] | flatten }}"
  loop: "{{ all_gids_l1 }}"

- name: ensure UID/GID and names uniqueness
  vars:
    duplicate_uid: "{{ all_uids_l2 | map(attribute='id') | community.general.counter | dict2items | selectattr('value', '>', 1) | map(attribute='key') }}"
    duplicate_gid: "{{ all_gids_l2 | map(attribute='id') | community.general.counter | dict2items | selectattr('value', '>', 1) | map(attribute='key') }}"
    duplicate_username: "{{ all_uids_l2 | map(attribute='name') | community.general.counter | dict2items | selectattr('value', '>', 1) | map(attribute='key') }}"
    duplicate_groupname: "{{ all_gids_l2 | map(attribute='name') | community.general.counter | dict2items | selectattr('value', '>', 1) | map(attribute='key') }}"
  assert:
    that:
      - duplicate_uid | length == 0
      - duplicate_gid | length == 0
      - duplicate_username | length == 0
      - duplicate_groupname | length == 0
    msg: "'id' and 'name' fields in users and groups (uid_ and gid_ in '$conf_dir/users') MUST be unique. There are duplicate(s) in : duplicate_uid: {{ duplicate_uid }}, duplicate_gid: {{ duplicate_gid }}, duplicate_username: {{ duplicate_username }}, duplicate_groupname: {{ duplicate_groupname }}"
  when: false # FIXME this should be done
