- set_fact:
    l_uids: "{{ l_uids | default([]) + [lookup('vars', item)] }}"
  loop: "{{ lookup('vars', u.uids) }}"

- set_fact:
    l_gids: "{{ l_gids | default([]) + [lookup('vars', item)] }}"
  loop: "{{ lookup('vars', u.gids) }}"

- include_tasks: _nested_user_group_create_sub_g.yml
  vars:
    g: "{{ it }}"
  loop: "{{ l_gids }}"
  loop_control:
    loop_var: it

- include_tasks: _nested_user_group_create_sub_u.yml
  vars:
    u: "{{ it }}"
  loop: "{{ l_uids }}"
  loop_control:
    loop_var: it

- include_tasks: _nested_user_group_create_sub_ug.yml
  vars:
    u: "{{ it[0] }}"
    g: "{{ it[1] }}"
  loop: "{{ l_uids | product(l_gids) | list }}"
  loop_control:
    loop_var: it
