- name: create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.id | default(omit) }}"
    comment: "{{ item.email | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    system: "{{ item.system | default(omit) }}"
    update_password: on_create
  with_items:
    - "{{ u }}"

- name: users authorized_key
  ansible.posix.authorized_key:
    manage_dir: true
    user: "{{ item }}"
    key: "{{ lookup('file', conf_dir ~ '/authorized_keys/' ~ item ~ '.pub') }}"
  with_items:
    - "{{ u | map(attribute='name') }}"

- name: revoked users authorized_key
  ansible.posix.authorized_key:
    manage_dir: true
    user: "{{ item }}"
    key: "{{ lookup('file', conf_dir ~ '/authorized_keys/REVOKED.pub') }}"
    state: "absent"
  with_items:
    - "{{ u | map(attribute='name') }}"

- name: Allow mounting cifs shares
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ item | regex_replace('\\.','') }}"
    mode: 0440
    create: true
    regexp: "^{{ item }} ALL=NOPASSWD:/bin/mount -t cifs"
    line: "{{ item }} ALL=NOPASSWD:/bin/mount -t cifs //*/* /home/{{ item }}/* *"
    validate: /usr/sbin/visudo -cf %s
  with_items:
    - "{{ u | map(attribute='name') }}"

- name: Allow umounting cifs shares
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ item | regex_replace('\\.','') }}"
    mode: 0440
    create: true
    regexp: "^{{ item }} ALL=NOPASSWD:/bin/umount"
    line: "{{ item }} ALL=NOPASSWD:/bin/umount /home/{{ item }}/* *"
    validate: /usr/sbin/visudo -cf %s
  with_items:
    - "{{ u | map(attribute='name') }}"
