- name: Allow mounting cifs shares
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ item | regex_replace('\\.','') }}"
    mode: 0440
    create: true
    regexp: "^{{ item }} ALL=NOPASSWD:/bin/mount -t cifs"
    line: "{{ item }} ALL=NOPASSWD:/bin/mount -t cifs //*/* /home/{{ item }}/* *"
    validate: /usr/sbin/visudo -cf %s
  with_items:
    - "{{ u | map(attribute='name') }}"

- name: Allow umounting cifs shares
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ item | regex_replace('\\.','') }}"
    mode: 0440
    create: true
    regexp: "^{{ item }} ALL=NOPASSWD:/bin/umount"
    line: "{{ item }} ALL=NOPASSWD:/bin/umount /home/{{ item }}/* *"
    validate: /usr/sbin/visudo -cf %s
  with_items:
    - "{{ u | map(attribute='name') }}"
