- name: Create users+groups
  include_tasks: _nested_user_group_create.yml
  vars:
    u: "{{ item_users }}"
    sup_gids:
      - id: 100
        name: 'users'
      - system: true
        name: 'sudonopass'
      - system: true
        name: 'adm'
      - system: true
        name: 'plugdev'
  with_items: "{{ admins }}"
  loop_control:
    loop_var: item_users

- name: sudo without password
  community.general.sudoers:
    name: admin-nopass
    group: sudonopass
    commands: ALL
