- name: Create users+groups
  include_tasks: _nested_user_group_create.yml
  vars:
    u: "{{ item_users }}"
    sup_gids:
      - id: 100
        name: 'users'
  with_items: "{{ users }}"
  loop_control:
    loop_var: item_users

##############################################################################
# We need HOME for login users (including root)
##############################################################################

- name: Create users list
  include_tasks: _nested_user_list.yml
  vars:
    u: "{{ item_users }}"
  with_items: "{{ admins + users }}"
  loop_control:
    loop_var: item_users

- set_fact:
    all_users: "{{ u | flatten | unique(attribute='name') | map(attribute='name') + ['root'] }}"

- name: Get user's info
  ansible.builtin.user:
    name: "{{ item }}"
  with_items:
    - "{{ all_users }}"
  register: all_users_info

- name: $HOME list
  set_fact:
    homes: "{{ all_users_info.results }}"

- debug:
    msg: "{{ all_users_info.results }}"

##############################################################################
# Overwrite defaults for user who have never login
##############################################################################
- name: skel needed?
  check_mode: false
  no_log: true
  ansible.builtin.shell: |
    if ls -lh {{ item.home }}/.bash_history ; then
      return 0
    fi
    if ls -lh {{ item.home }}/.zsh_history ; then
      return 0
    fi
    return 1
  with_items:
    - "{{ homes }}"
  register: skel_needed
  changed_when: false
  failed_when: skel_needed.rc != 0 and skel_needed.rc != 1

- name: $HOME list (skel needed)
  set_fact:
    skel_homes: "{{ skel_needed.results | selectattr('rc', 'equalto', 1) }}"

- name: skel copy
  no_log: true
  ansible.builtin.copy:
    owner: "{{ item.item.uid }}"
    group: "{{ item.item.group }}"
    src: "{{ conf_dir ~ '/files/skel/' }}"
    dest: "{{ item.item.home }}"
  with_items: "{{ skel_needed.results }}"

- name: enable bash colors (for tty and sudo)
  no_log: true
  ignore_errors: true
  lineinfile:
    dest: "{{ item.home }}/.bashrc"
    regexp: "^#force_color_prompt=yes"
    line: "force_color_prompt=yes"
    state: present
  with_items:
    - "{{ homes }}"

- name: bash color red for root
  ignore_errors: true
  lineinfile:
    dest: "/root/.bashrc"
    regexp: '(    PS1=.*)(\[01;32m\\]\\u)(.*)'
    line: '\g<1>[01;31m\\]\\u\g<3>'
    backrefs: yes
    state: present

##############################################################################
# Create per user storage and simlinks
# FIXME : where to put this?
##############################################################################

- name: per user storage .apptainer
  when: ansible_facts['hostname'] == 'disco' or ansible_facts['hostname'] == 'chacha'
  ansible.builtin.file:
    path: "/data/disk01/apptainer/{{ item }}/.apptainer"
    state: directory
    owner: "{{item}}"
    group: "{{item}}"
  with_items: "{{ all_users }}"

- name: per user storage datasets
  when: ansible_facts['hostname'] == 'disco' or ansible_facts['hostname'] == 'chacha'
  ansible.builtin.file:
    path: "/data/space/datasets/{{ item }}"
    state: directory
    owner: "{{item}}"
    group: "{{item}}"
  with_items: "{{ all_users }}"

- name: per user storage results
  when: ansible_facts['hostname'] == 'disco'
  ansible.builtin.file:
    path: "/data/shared/{{ item }}/results"
    state: directory
    owner: "{{item}}"
    group: "{{item}}"
  with_items: "{{ all_users }}"

- name: per user storage shared_datasets
  when: ansible_facts['hostname'] == 'disco'
  ansible.builtin.file:
    path: "/data/shared/{{ item }}/shared_datasets"
    state: directory
    owner: "{{item}}"
    group: "{{item}}"
  with_items: "{{ all_users }}"

##############################################################################

- name: per user storage link .apptainer
  ignore_errors: true
  when: ansible_facts['hostname'] == 'disco' or ansible_facts['hostname'] == 'chacha'
  ansible.builtin.file:
    state: link
    src: "/data/disk01/apptainer/{{ item.item }}/.apptainer"
    dest: "{{ item.home }}/.apptainer"
    force: yes
  with_items: "{{ all_users_info.results }} "

- name: per user storage link datasets
  ignore_errors: true
  when: ansible_facts['hostname'] == 'disco' or ansible_facts['hostname'] == 'chacha'
  ansible.builtin.file:
    state: link
    src: "/data/space/datasets/{{ item.item }}"
    dest: "{{ item.home }}/datasets"
    force: yes
  with_items: "{{ all_users_info.results }} "

- name: per user storage link results
  ignore_errors: true
  when: ansible_facts['hostname'] == 'disco' or ansible_facts['hostname'] == 'chacha'
  ansible.builtin.file:
    state: link
    src: "/data/shared/{{ item.item }}/results"
    dest: "{{ item.home }}/results"
    force: yes
  with_items: "{{ all_users_info.results }} "

- name: per user storage link shared_datasets
  ignore_errors: true
  when: ansible_facts['hostname'] == 'disco' or ansible_facts['hostname'] == 'chacha'
  ansible.builtin.file:
    state: link
    src: "/data/shared/{{ item.item }}/shared_datasets"
    dest: "{{ item.home }}/shared_datasets"
    force: yes
  with_items: "{{ all_users_info.results }} "
