- name: Create users+groups
  include_tasks: _nested_user_group_create.yml
  vars:
    u: "{{ item_users }}"
    sup_gids:
      - id: 100
        name: 'users'
  with_items: "{{ users }}"
  loop_control:
    loop_var: item_users

##############################################################################
# We need HOME for login users (including root)
##############################################################################

- name: Create users list
  include_tasks: _nested_user_list.yml
  vars:
    u: "{{ item_users }}"
  with_items: "{{ admins + users }}"
  loop_control:
    loop_var: item_users

- set_fact:
    all_users: "{{ u | flatten | unique(attribute='name') | map(attribute='name') + ['root'] }}"

- name: Get user's info
  ansible.builtin.user:
    name: "{{ item }}"
  with_items:
    - "{{ all_users }}"
  register: all_users_info

- name: $HOME list
  set_fact:
    homes: "{{ all_users_info.results }}"

##############################################################################
# Overwrite defaults for user who have never login
##############################################################################
- name: skel needed?
  check_mode: false
  no_log: true
  ansible.builtin.shell: |
    if ls -lh {{ item.home }}/.bash_history ; then
      return 0
    fi
    if ls -lh {{ item.home }}/.zsh_history ; then
      return 0
    fi
    return 1
  with_items:
    - "{{ homes }}"
  register: skel_needed
  changed_when: false
  failed_when: skel_needed.rc != 0 and skel_needed.rc != 1

- name: $HOME list (skel needed)
  set_fact:
    skel_homes: "{{ skel_needed.results | selectattr('rc', 'equalto', 1) }}"

- name: skel copy
  no_log: true
  ansible.builtin.copy:
    owner: "{{ item.item.uid }}"
    group: "{{ item.item.group }}"
    src: "{{ conf_dir ~ '/files/skel/' }}"
    dest: "{{ item.item.home }}"
  with_items: "{{ skel_needed.results }}"

- name: enable bash colors (for tty and sudo)
  no_log: true
  lineinfile:
    dest: "{{ item.home }}/.bashrc"
    regexp: "^#force_color_prompt=yes"
    line: "force_color_prompt=yes"
    state: present
  with_items:
    - "{{ homes }}"

- name: bash color red for root
  lineinfile:
    dest: "/root/.bashrc"
    regexp: '(    PS1=.*)(\[01;32m\\]\\u)(.*)'
    line: '\g<1>[01;31m\\]\\u\g<3>'
    backrefs: yes
    state: present
